# Generated by Django 4.2.1 on 2023-05-23 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import haydi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mekan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=20, verbose_name='Mekan Adı')),
                ('adres', models.CharField(max_length=300)),
                ('telefon_numarasi', models.CharField(max_length=11, verbose_name='Telefon')),
                ('webadresi', models.URLField(verbose_name='Website Adresi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Adresi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Mekan Açıklaması')),
                ('onayli', models.BooleanField(default=False, verbose_name='Onaylı')),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('ilce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.subregion')),
                ('sehir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sehir', to='cities_light.region')),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20)),
                ('soyad', models.CharField(max_length=20)),
                ('profile_img', models.ImageField(default='default.jpg', upload_to=haydi.models.user_directory_path)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=11, null=True)),
                ('kullanici_adi', models.CharField(blank=True, max_length=150, null=True)),
                ('sifre', models.CharField(blank=True, max_length=128, null=True)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, verbose_name='Etkinlik Adı')),
                ('baslik', models.CharField(blank=True, max_length=50, null=True, verbose_name='Baslik')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('saat', models.TimeField(verbose_name='Saat')),
                ('gün', models.DateTimeField(verbose_name='Etkinlik Günü')),
                ('açiklama', models.TextField(blank=True)),
                ('katilimcilar', models.ManyToManyField(blank=True, related_name='katilimci_event_set', to='haydi.eventuser')),
                ('mekan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='haydi.mekan')),
                ('yönetici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yönetici_event_set', to='haydi.eventuser')),
            ],
        ),
    ]
