# Generated by Django 4.2.1 on 2023-05-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='kullanici_adi',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='sifre',
        ),
    ]
