# Generated by Django 4.1.7 on 2023-05-24 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haydi', '0002_remove_eventuser_kullanici_adi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20)),
                ('soyad', models.CharField(max_length=20)),
                ('profile_img', models.ImageField(default='default.jpg', upload_to='profile_images/')),
                ('telefon', models.CharField(blank=True, max_length=11, null=True)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='katilimcilar',
        ),
        migrations.AlterField(
            model_name='event',
            name='yönetici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yönetici_event_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EventUser',
        ),
    ]
