# Generated by Django 4.1.7 on 2023-05-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0005_katilimci'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='katilimci',
            unique_together=set(),
        ),
    ]
