# Generated by Django 4.1.7 on 2023-05-24 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haydi', '0006_alter_katilimci_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='katilimcilar',
            field=models.ManyToManyField(blank=True, related_name='katildigi_etkinlikler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Katilimci',
        ),
    ]
