# Generated by Django 4.2.1 on 2023-05-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0007_event_katilimcilar_delete_katilimci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
