# Generated by Django 4.2.1 on 2023-05-25 12:34

from django.db import migrations, models
import haydi.models


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0009_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(upload_to=haydi.models.user_directory_path),
        ),
    ]
