# Generated by Django 4.2.1 on 2023-05-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0010_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_count',
            field=models.IntegerField(default=0),
        ),
    ]
