# Generated by Django 4.2.1 on 2023-05-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0012_profile_katildigi_etkinlikler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='katildigi_etkinlikler',
        ),
    ]
