# Generated by Django 4.1.7 on 2023-05-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0014_profile_katildigi_etkinlikler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activity_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='olusturdugu_etkinlikler',
            field=models.ManyToManyField(blank=True, related_name='olusturan_profil', to='haydi.event'),
        ),
    ]
