# Generated by Django 4.1.7 on 2023-05-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0015_remove_profile_activity_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='silindi',
            field=models.BooleanField(default=False),
        ),
    ]
