# Generated by Django 4.2.1 on 2023-05-29 08:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0016_event_silindi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='açiklama',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
