# Generated by Django 4.2.1 on 2023-05-31 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haydi', '0019_profile_olusturdugu_mekanlar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='olusturdugu_mekanlar',
        ),
        migrations.AddField(
            model_name='mekan',
            name='olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
