# Generated by Django 4.2.1 on 2023-06-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0020_remove_profile_olusturdugu_mekanlar_mekan_olusturan'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='katilimci_sayisi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
