# Generated by Django 4.2.1 on 2023-06-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0022_event_katilimci_kontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='katilimci_sayisi',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
