# Generated by Django 4.2.1 on 2023-06-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0023_alter_event_katilimci_sayisi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='katilimci_sayisi',
            new_name='kontenjan',
        ),
    ]
