# Generated by Django 4.2.1 on 2023-06-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0025_yorum'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='silindi',
            field=models.BooleanField(default=False),
        ),
    ]
