# Generated by Django 4.2.1 on 2023-06-06 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("haydi", "0026_yorum_silindi"),
    ]

    operations = [
        migrations.CreateModel(
            name="YorumCevap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("silindi", models.BooleanField(default=False)),
                (
                    "cevapsahibi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "yorum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="haydi.yorum"
                    ),
                ),
            ],
        ),
    ]
