# Generated by Django 4.2.1 on 2023-06-06 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("haydi", "0027_yorumcevap"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yorumcevap",
            old_name="yorum",
            new_name="cevap",
        ),
    ]
