# Generated by Django 4.2.1 on 2023-06-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("haydi", "0029_alter_yorumcevap_cevap"),
    ]

    operations = [
        migrations.AddField(
            model_name="yorumcevap",
            name="yorum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cevaplar",
                to="haydi.yorum",
            ),
        ),
        migrations.AlterField(
            model_name="yorumcevap",
            name="cevap",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
