# Generated by Django 4.2.1 on 2023-06-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haydi", "0033_alter_mekan_kapali"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mekan",
            name="kapali",
        ),
        migrations.AddField(
            model_name="mekan",
            name="acik",
            field=models.BooleanField(default=False, verbose_name="Etkinliğe Açık"),
        ),
    ]
