# Generated by Django 4.2.1 on 2023-06-09 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("haydi", "0035_mekan_olumlu_oy_mekan_olumsuz_oy"),
    ]

    operations = [
        migrations.AddField(
            model_name="mekan",
            name="olumlu_oy_kullananlar",
            field=models.ManyToManyField(
                related_name="olumlu_oylar", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mekan",
            name="olumsuz_oy_kullananlar",
            field=models.ManyToManyField(
                related_name="olumsuz_oylar", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
