# Generated by Django 4.2.1 on 2023-06-16 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("haydi", "0039_bildirim"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bildirim",
            old_name="etkileşim",
            new_name="etkilesim",
        ),
        migrations.AddField(
            model_name="bildirim",
            name="bildirim_alani",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bildirimler",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
