# Generated by Django 4.1.7 on 2023-06-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0042_profile_bildirim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bildirim',
        ),
        migrations.AddField(
            model_name='profile',
            name='bildirimler',
            field=models.ManyToManyField(related_name='bildirim_alanlari', to='haydi.bildirim'),
        ),
    ]
