# Generated by Django 4.1.7 on 2023-06-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0043_remove_profile_bildirim_profile_bildirimler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildirim',
            name='bildirim_alani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler1', to='haydi.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bildirimler',
            field=models.ManyToManyField(blank=True, null=True, related_name='bildirim_alani1', to='haydi.bildirim'),
        ),
    ]
