# Generated by Django 4.2.1 on 2023-06-19 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("haydi", "0045_profile_bildirim_sayisi"),
    ]

    operations = [
        migrations.AddField(
            model_name="bildirim",
            name="olusturulma_tarihi",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
