# Generated by Django 4.2.1 on 2023-06-19 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("haydi", "0046_bildirim_olusturulma_tarihi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bildirim",
            name="olusturulma_tarihi",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="mekan",
            name="onayli",
            field=models.BooleanField(default=True, verbose_name="Onaylı"),
        ),
    ]
