# Generated by Django 4.0.10 on 2023-06-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0047_alter_bildirim_olusturulma_tarihi_alter_mekan_onayli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ad',
            field=models.CharField(max_length=50, verbose_name='Etkinlik Adı'),
        ),
    ]
