# Generated by Django 4.0.10 on 2023-06-26 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haydi', '0048_alter_event_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='engelli_listesi',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
