# Generated by Django 4.0.10 on 2023-06-26 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haydi', '0049_event_engelli_listesi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='engelli_listesi',
        ),
        migrations.AddField(
            model_name='profile',
            name='engelli_listesi',
            field=models.ManyToManyField(blank=True, null=True, related_name='engelli', to=settings.AUTH_USER_MODEL),
        ),
    ]
