# Generated by Django 4.0.10 on 2023-07-05 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haydi', '0050_remove_event_engelli_listesi_profile_engelli_listesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='takip_ettiklerim',
            field=models.ManyToManyField(blank=True, null=True, related_name='takip_edilen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='takipçiler',
            field=models.ManyToManyField(blank=True, null=True, related_name='takipçilerim', to=settings.AUTH_USER_MODEL),
        ),
    ]
