# Generated by Django 4.0.10 on 2023-07-05 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haydi', '0051_profile_takip_ettiklerim_profile_takipçiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirim',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kullanici', to=settings.AUTH_USER_MODEL),
        ),
    ]
