# Generated by Django 4.1.7 on 2023-07-11 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haydi', '0052_bildirim_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='negatif_oy',
            field=models.ManyToManyField(blank=True, null=True, related_name='negatif_oylar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='pozitif_oy',
            field=models.ManyToManyField(blank=True, null=True, related_name='pozitif_oylar', to=settings.AUTH_USER_MODEL),
        ),
    ]
