# Generated by Django 4.1.7 on 2023-07-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0054_rename_negatif_oy_profile_negatif_oylar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pozitif_oy_sayisi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
