# Generated by Django 4.1.7 on 2023-07-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0056_remove_profile_pozitif_oy_sayisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pozitif_oy_sayisi',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
