# Generated by Django 4.1.7 on 2023-07-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0059_profile_pozitif_oy_sayisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pozitif_oy_sayisi',
        ),
    ]
