# Generated by Django 4.1.7 on 2023-07-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('haydi', '0060_remove_profile_pozitif_oy_sayisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='yetkiler',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
