# Generated by Django 4.1.7 on 2023-07-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haydi', '0061_profile_yetkiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='takipçiye_özel',
            field=models.BooleanField(default=False),
        ),
    ]
